# https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
language: c
sudo: false

os: linux
addons: {apt: {packages: [xsltproc, docbook-xsl-ns, docbook-xsl-saxon, libsaxonhe-java, fop]}}

addons:
 apt:
   sources:
   - debian-sid
   packages:
   - xsltproc
   - docbook-xsl-ns
   - docbook-xsl-saxon
   - libsaxonhe-java
   - fop

script:
  - ./generateforrelease.sh
