# https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
language: c
sudo: false

os: linux
addons: {apt: {packages: [xsltproc, docbook-xsl-ns, docbook-xsl-saxon, libsaxonb-java, fop]}}

script:
  - sed -i -e 's:/Users/dclunie/Documents/Work/DICOM_Publish_XML/DocBookDICOM2013/:$CUR:' olinkdb_pdf.xml
  - sed -i -e 's:/opt/local/share/java/saxon9he.jar:/usr/share/java/saxonb.jar:' *.sh
  - ./generateforrelease.sh
